Implement std::error::Error for TemporalError (#664)
Currently, `TemporalError` does not implement `std::error::Error`, which
makes `TemporalResult` incompatible with ecosystem crates for error
conversions, such as `anyhow`.

The fix is a simple one-line addition to implement the error trait,
since `TemporalError` already implements `Display` and `Debug`.

---------

Co-authored-by: Leandro Vandari <leandrovandari@gmail.com>